const express = require("express");
const router = express.Router();
const mediaController = require("../controllers/media.controller");
const auth = require("../middlewares/auth.middleware");
const role = require("../middlewares/role.middleware");
const uploadMedia = require("../middlewares/uploadMedia");
router.use(auth);
router.use(role("ADMIN", "CLIENT"));
router.delete("/delete", mediaController.deleteMedia);
router.post("/replace", uploadMedia.single("file"), mediaController.replaceMedia);
module.exports = router;