// USO DE LA HERRAMIENTA
const USO_HERRAMIENTA = {
  NEGOCIO: "NEGOCIO",
  EQUIPO_COMERCIAL: "EQUIPO_COMERCIAL",
  APRENDER: "APRENDER",
  PROYECTO_PERSONAL: "PROYECTO_PERSONAL"
};

// OBJETIVO
const OBJETIVO = {
  AUMENTAR_VENTAS: "AUMENTAR_VENTAS",
  AUTOMATIZAR_RESPUESTAS: "AUTOMATIZAR_RESPUESTAS",
  ORGANIZAR_CONTACTOS_O_IDEAS: "ORGANIZAR_CONTACTOS_O_IDEAS",
  SOLO_VER_FUNCIONAMIENTO: "SOLO_VER_FUNCIONAMIENTO"
};

module.exports = {
  USO_HERRAMIENTA,
  OBJETIVO
};
